[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
broadcast = "broadcast"
ffi = false
fs_permissions = [{ access = "read-write", path = "./" }]
gas_limit = 30_000_000
verbosity = 2
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200
via_ir = false
solc_version = "0.8.24"

# Etherlink configuration
[rpc_endpoints]
etherlink_testnet = "https://node.ghostnet.etherlink.com"
etherlink_mainnet = "https://node.mainnet.etherlink.com"
local = "http://localhost:8545"

[etherscan]
etherlink_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet.explorer.etherlink.com/api" }
etherlink_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.etherlink.com/api" }

# Format settings
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

# Dependencies
# openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v5.0.1" }
# openzeppelin-contracts-upgradeable = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable.git", tag = "v5.0.0" }
# forge-std = { git = "https://github.com/foundry-rs/forge-std", tag = "v1.7.6" } 